### ISSUE TITLE
Use as node module

### ISSUE THREAD

**Issue by poloagustin** [Shnoo/js-CIE-1931-rgb-color-converter#1]
**Is your feature request related to a problem? Please describe.**
I would love to use this library in my node web service. I would need the `ColorConverter` class to be exported as a module in the script.

**Describe the solution you'd like**
The ideal way would be to be able to import the module as this `const ColorConverter = require('cie-rgb-color-converter')`

**Describe alternatives you've considered**
I have not yet come around to a workaround other than downloading your script and putting it in a file within my project. (I'm using typescript so a type declarations file would also help a lot)

**Additional context**
N/A

**Comment by Shnoo** [comment]
there is a project hostet on npm i'm not familiar with typescript so i'm sorry if this does not work for you.

see **https://www.npmjs.com/package/cie-rgb-color-converter** it exports it as a module via:

module.exports = ColorConverter
