### ISSUE TITLE
Incorrect xyBriToRgb conversion

### ISSUE THREAD

**Issue by qu4ntum4** [Shnoo/js-CIE-1931-rgb-color-converter#2]
Hello,

i'm trying to convert 
X : 0.4013 
Y : 0.2359 
Bri : 254

by calling : 
ColorConverter.xyBriToRgb(0.4013,0.2359,254);

which gives me : {r: 349, g: 188, b: 305}

that are incorrect values. 

Is there anything wrong ?

Thx

**Comment by Shnoo** [comment]
Yes the code was missing an out of bound check for the RGB Conversion.

Its Fixed now
