### ISSUE TITLE
ColorConverter.js has a capitalization mismatch in NPM

### ISSUE THREAD

**Issue by NotNite** [Shnoo/js-CIE-1931-rgb-color-converter#3]
In NPM, when I try and install this, it gives me this:
`
Error: Cannot find module '/home/julian/lightning/node_modules/cie-rgb-color-converter/colorConverter.js'. Please verify that the package.json has a valid "main" entry
`
The issue is the file is called "ColorConverter.js". Changing the file name to colorConverter.js worked, but should be fixed.

**Comment by Shnoo** [comment]
Sry i had a lot of other things to do over the last few months and didn't  realize there where issues on this repository due to lack usage. I will fix those as soon as possible.

**Comment by Shnoo** [comment]
Should be fixed now
