### ISSUE TITLE
Failing to convert to rgb

### ISSUE THREAD

**Issue by EFXPROMedia** [Shnoo/js-CIE-1931-rgb-color-converter#4]
When using ColorConverter.xyBriToRgb(x ,y , brightness); I am getting some of the channels of RGB negative like:

for `xy: [ 0.532, 0.4422 ] & bri: 254`
the result is `rgb: { r: 255, g: 231, b: -0 } }`

I have called the function after a sync request to get the light status once the response is returned I then:

`ColorConverter.xyBriToRgb(response.data.state.xy[0], response.data.state.xy[1], response.data.state.bri);`

**Comment by NotNite** [comment]
Bump. Library seems unmaintained, any alternatives? :/

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
same here :(

**Comment by Shnoo** [comment]
Sry i had a lot of other things to do over the last few months and didn't  realize there where issues on this repository due to lack usage. I will fix those as soon as possible.

**Comment by Shnoo** [comment]
Should be fixed now
